[package]
name = "ula-compose"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
snafu = "0.9.2"
noyalib = "0.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
tap = "1.0.1"
ula-protocol = { path = "../ula-protocol" }
smol = "2.0.2"
async-broadcast = "0.7.2"
asynchronous-codec = "0.7.0"
futures-util = { version = "0.3.31", default-features = false, features = [
    "std",
    "sink",
] }
log = "0.4.34"
env_logger = { version = "0.11.11", default-features = false, features = [
    "auto-color",
    "humantime",
] }
